### ISSUE TITLE
MRAA direction missing

### ISSUE THREAD

**Issue by vmcbaptista** [Drunkar/NeoPixel-edison-mraa#1]
By default edison puts pins in input mode, if you execute the example after startup it won't work.
I solved this adding
` mraa_gpio_dir(gpio, MRAA_GPIO_OUT);`  
on function `NPInit` of  `Neopixel.c`

With this every time you initialize the LED you define the pin to output direction.

**Comment by Drunkar** [comment]
Hi @vmcbaptista , thanks alot for reporting !
Oh, I didn't notice that. Maybe my edison had been already set upped.
If you have enough time, can you make a pull request to merge this change?
Thanks!

**Comment by Drunkar** [comment]
#2 

Thanks!
